### ISSUE TITLE
Feature: More header/footer customizations

### ISSUE THREAD

**Issue by unleed-l** [AppFlowy-IO/appflowy-board#22]
Actually we can't change header/footer decoration, would be great to be able to do that.

**Comment by Xazin** [comment]
Hey Unleed, you can use the Footer and Header builder to build footer/header for a Group.

Do you mean footer/header for the whole board? In that case, since the board is scrollable horizontally, would these be in the scrollable body?

**Comment by Xazin** [comment]
Closed as stale as we didn't get a response on the expected behavior of this change.
